name: Publish
on: 
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          architecture: x64
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm -F "@thuantan2060/nestjs-redis" run build
      - run: pnpm -F "@thuantan2060/nestjs-redis" publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
