name: Testing
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Node.js 22 'Jod' (LTS)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          architecture: x64
          cache: 'pnpm'
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('compose.yaml') }}
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: './compose.yaml'
          up-flags: '-d'
          down-flags: '-v'
      - run: docker compose exec cluster-m1 redis-cli -a mycluster --cluster create 127.0.0.1:7380 127.0.0.1:7381 127.0.0.1:7382 --cluster-yes
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F "@thuantan2060/nestjs-redis" run lint
      - run: pnpm -F "@thuantan2060/nestjs-redis" run test
      - run: pnpm -F "@thuantan2060/nestjs-redis" run test:e2e
